---
- name: Get secure password from /dev/random
  ansible.builtin.shell:
    "head -c {{ num_bytes }} /dev/random | base64"
  register: password_gen
  vars:
    num_bytes: 32

- name: save oatbert password on the deployed VM for debugging
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sonic      #kindof like /etc/shadow ig
    line: 'User:\tOatbert\tPassword:\t{{password_gen.stdout}}'
    mode: 400
    create: true

- name: Hash the password so ansible doesn't complain.
  ansible.builtin.shell: "echo '{{ password_gen.stdout }}' | mkpasswd --method=sha-512 --stdin"
  register: hashed_password

- name: create oatbert user in system
  become: true
  ansible.builtin.user:
    name: oatbert
    password: '{{ hashed_password.stdout }}'

- name: Create legislation database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: legislation
    login_password:  '{{ password_gen.stdout }}'
    login_user: oatbert

- name: Regester oatbert user in postgres
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: oatbert
    db: legislation
    password: '{{ password_gen.stdout }}'

